version: '3.7'

services:

  minio:
    image: minio/minio
    volumes:
        - minio-data:/export
    ports:
        - 9000:9000
    environment:
        MINIO_ACCESS_KEY: access_key
        MINIO_SECRET_KEY: secret_key
    command: server /export --address=:9000

  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=890306
      - POSTGRES_DB=callback_news
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: iraidabarreto07@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: 890306
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"

volumes:
  postgres_data:
  minio-data:
  pgadmin-data:     